import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
// const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import { Bell } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CsSidebar } from "@/components/circles/CsSidebar";
import { CsHeader } from "@/components/circles/CsHeader";
import { CsHeading } from "@/components/circles/CsHeading";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  currentPage,
}: Readonly<{
  children: React.ReactNode;
  currentPage: CurrentPage;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <div className="hidden border-r bg-muted/40 md:block">
            <div className="flex h-full max-h-screen flex-col gap-2">
              <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                <Link
                  href="/"
                  className="flex items-center gap-2 text-3xl font-federal"
                >
                  <span className="">Circles</span>
                </Link>
                <Button
                  variant="outline"
                  size="icon"
                  className="ml-auto h-8 w-8"
                >
                  <Bell className="h-4 w-4" />
                  <span className="sr-only">Toggle notifications</span>
                </Button>
              </div>
              <div className="flex-1">
                <CsSidebar currentPage={currentPage} />
              </div>
            </div>
          </div>
          <div className="flex flex-col h-full">
            <CsHeader />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
